### ISSUE TITLE
feat: add dark mode and toggling support

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#5] opened 2020-08-08 06:41 UTC
I've heard that viewing blue light before bed is harmful to sleep quality, so I want to work on changing the site's theme to be more conducive toward optimal sleep hygiene.

Current appearance of freesound-player's homepage at the time of this issue's creation:

![freesound-player current background blue 2020-08-07 233857](https://user-images.githubusercontent.com/43425812/89704276-53136580-d907-11ea-8c46-0521ea850357.jpg)

**Comment by amilajack** [comment] 2020-08-13 19:53
We could use https://github.com/GoogleChromeLabs/dark-mode-toggle for this

**Comment by amilajack** [comment] 2020-09-08 02:39
Duplicate of #29

**Closed** 2020-09-08 02:39 UTC
Labels: enhancement
